### ISSUE TITLE
Change the colour theme to somewhat lighter/brighter colour 

### ISSUE THREAD

**Issue by somyaranjan26** [sharmaaditya570191/BossY#60]
Change the colour theme to somewhat lighter/brighter colour which will become day mode.

**Comment by Adyasha8105** [comment]
I want to work on this issue @somyaranjan26

**Comment by avinash2201** [comment]
Hey,I want to work on this issue

**Comment by Adyasha8105** [comment]
@somyaranjan26 Can you just elaborate the issue?

**Comment by Adyasha8105** [comment]
@somyaranjan26 As the images present inside the site are white in color and the logo, red in color which can't be changed. Also, the site is made on the basis of dark mode that's why all colors are arranged accordingly. Now I have to change it into day mode so light colors are most preferable to it but it will match with those images. 
Lemme know what you think?

**Comment by somyaranjan26** [comment]
@Adyasha8105 for now, you can add your icons and logos according to your style. If it looks fine, we will continue with it otherwise later we will create an issue for logos and icons. And sorry for being late in replying.

**Comment by shreyakapoor08** [comment]
@somyaranjan26 can I work on this ?

**Comment by shreyakapoor08** [comment]
@somyaranjan26 Hey, I have gone through many websites and thought of giving it this color palette. Please let me know if it is fine. Or anything else has to be done.
